apiVersion: apps/v1
kind: Deployment
metadata:
  name: score-api
  namespace: gamecloud
  labels:
    app: score-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: score-api
  template:
    metadata:
      labels:
        app: score-api
    spec:
      containers:
        - name: score-api
          image: gamecloud/score-api:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gamecloud-secrets
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gamecloud-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gamecloud-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gamecloud-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: score-service
  namespace: gamecloud
spec:
  selector:
    app: score-api
  ports:
    - port: 80
      targetPort: 3003
  type: ClusterIP
