apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: gamecloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: gamecloud/auth-api:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gamecloud-secrets
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gamecloud-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gamecloud-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gamecloud-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: gamecloud
spec:
  selector:
    app: auth-api
  ports:
    - port: 80
      targetPort: 5001
